export { default as icArrow } from './ic_arrow.svg';
export { default as icDelete } from './ic_delete.svg';
export { default as icSearch } from './ic_search.svg';
export { default as icCloseButton } from './ic_close_button.svg';
export { default as icGuide } from './ic_guide.svg';
export { default as icGuideHighlight } from './ic_guide_highlight.svg';
export { default as icGuideSpacing } from './ic_guide_spacing.svg';
export { default as icXButton } from './ic_x_button.svg';
export { default as icScript } from './ic_script.svg';
